# Setup
title:        2graphic presents Sinap
tagline:      A Visual IDE for Graph-Based Languages
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       2graphic
  url:        https://github.com/2graphic 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown